name: Pull Request check of markdown files

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Markdown Files Format
      run: |
        IFS=$'\n'
        for file in $(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep '\.md$'); do
          if ! grep -q -E '---\ntitle: .+\npublished: (true|false)\ndescription: .+\ntags: .+\ncover_image: .+\ncanonical_url: .+\nid: .+\n---' "$file"; then
            echo "The file \"$file\" does not have the required Markdown header format."
            exit 1
          fi
        done