name: Pull Request check of markdown files

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Markdown Files Format
      run: |
        while IFS= read -r file; do
          if ! grep -Pzoq -- '---\ntitle: .+\npublished: (true|false)\ndescription: .+\ntags: .+\ncover_image: http.+\ncanonical_url: null\nid: .*\n---' "$file"; then
            echo "File $file does not meet the required format"
            exit 1
          fi
        done < <(git diff --name-only --diff-filter=AM origin/main...HEAD -- '*.md')
